name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  intl: ^0.19.0

  # Firebase dependencies
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # Social sign-in
  google_sign_in: ^7.1.1
  google_sign_in_ios: ^6.1.0
  flutter_facebook_auth: ^6.0.3
  sign_in_with_apple: ^5.0.0

  # Navigation
  auto_route: ^7.9.0

  # State Management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/api/
    - assets/images/
    - assets/images/products/
    - assets/images/categories/
    - assets/icons/