name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # Social sign-in
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^5.0.0

  # Navigation
  auto_route: ^7.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
