// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_VSvL_Fe6IZTAN3uHRMY2Tg2R257G0S0',
    appId: '1:179088526879:web:b055d0f5141fb327350f2a',
    messagingSenderId: '179088526879',
    projectId: 'clot-3348f',
    authDomain: 'clot-3348f.firebaseapp.com',
    storageBucket: 'clot-3348f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFJl1vAWOXTpV3mUITrYGV_W1XGT-Nsw',
    appId: '1:179088526879:android:57d2ec28a8202d2e350f2a',
    messagingSenderId: '179088526879',
    projectId: 'clot-3348f',
    storageBucket: 'clot-3348f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJE0rgqwB4ZWTWVuNJAWlQ8q2sK-_Khmc',
    appId: '1:179088526879:ios:64c13da5e9575c39350f2a',
    messagingSenderId: '179088526879',
    projectId: 'clot-3348f',
    storageBucket: 'clot-3348f.firebasestorage.app',
    iosBundleId: 'com.almas.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJE0rgqwB4ZWTWVuNJAWlQ8q2sK-_Khmc',
    appId: '1:179088526879:ios:e0b9ea49ec95358f350f2a',
    messagingSenderId: '179088526879',
    projectId: 'clot-3348f',
    storageBucket: 'clot-3348f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_VSvL_Fe6IZTAN3uHRMY2Tg2R257G0S0',
    appId: '1:179088526879:web:ae00a0dc89e4734d350f2a',
    messagingSenderId: '179088526879',
    projectId: 'clot-3348f',
    authDomain: 'clot-3348f.firebaseapp.com',
    storageBucket: 'clot-3348f.firebasestorage.app',
  );
}
