platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

install! 'cocoapods',
  :deterministic_uuids => false

flutter_application_path = File.expand_path('..', __dir__)
load File.join(flutter_application_path, '.dart_tool', 'flutter_dependencies.rb')

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
